# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "cryptd" ];
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/7ad600f4-ffe8-4591-8824-229164c512e9";
  boot.initrd.luks.devices."cryptnewhd".device = "/dev/disk/by-uuid/97afe469-d1ae-4653-aa10-12d223493045";
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/lvmnix-root";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46FA-B3CA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/lvmnix-home";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/lvmnix-nix";
      fsType = "btrfs";
    };
   
   fileSystems."/new-hd" = 
     { device = "/dev/mapper/lvmnix-new-hd";
       fsType = "btrfs";
     };

  swapDevices =
    [ { device = "/dev/mapper/lvmnix-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
